#!/usr/bin/env cwl-runner
### Test harness for pm25_yearly_download.cwl

cwlVersion: v1.2
class: Workflow

requirements:
  InlineJavascriptRequirement: {}
  MultipleInputFeatureRequirement: {}
  ScatterFeatureRequirement: {}
  StepInputExpressionRequirement: {}
  SubworkflowFeatureRequirement: {}


# All inputs of original pipeline, remove what is not needed
inputs:
  component:
    default:
    - BC
    - NH4
    - NIT
    - OM
    - SO4
    - SOIL
    - SS
    type: string[]
  connection_name:
    doc: The name of the section in the database.ini file
    type: string
  database:
    doc: Path to database connection file, usually database.ini
    type: File
  downloads:
    doc: Directory, containing files, downloaded and unpacked from WUSTL box
    type: Directory
  geography:
    doc: 'Type of geography: zip codes or counties

      Valid values: "zip", "zcta" or "county"

      '
    type: string
  proxy:
    default: ''
    doc: HTTP/HTTPS Proxy if required
    type: string?
  shape_file_collection:
    default: tiger
    doc: "[Collection of shapefiles](https://www2.census.gov/geo/tiger), \neither\
      \ GENZ or TIGER\n"
    type: string
  strategy:
    default: downscale
    doc: Rasterization strategy
    type: string
  table:
    doc: The name of the table to store teh aggreagted data in
    type: string
  test_script:
    doc: File containing SQL test script
    type: File
  variable:
    default: PM25
    type: string
  years:
    default:
    - 2000
    - 2001
    - 2002
    - 2003
    - 2004
    - 2005
    - 2006
    - 2007
    - 2008
    - 2009
    - 2010
    - 2011
    - 2012
    - 2013
    - 2014
    - 2015
    - 2016
    - 2017
    type: int[]


steps:
  execute:
    run: pm25_yearly_download.cwl
    in:
      proxy: proxy
      downloads: downloads
      geography: geography
      years: years
      variable: variable
      component: component
      strategy: strategy
      shape_file_collection: shape_file_collection
      database: database
      connection_name: connection_name
      table: table
    out:
      - aggregate_data
      - data_dictionary
      - consolidated_data
      - shapes
      - aggregate_log
      - aggregate_err
      - ingest_log
      - index_log
      - vacuum_log
      - ingest_err
      - index_err
      - vacuum_err

  verify:
    run: run_test.cwl
    in:
      database: database
      connection_name: connection_name
      script: test_script
      depends_on: execute/vacuum_err
    out:
      - log
      - errors

outputs:
## Generated by nsaph/util/cwl_collect_outputs.py from pm25_yearly_download.cwl:
  execute_aggregate_data:
    type: File[]
    outputSource: execute/aggregate_data
  execute_data_dictionary:
    type: File
    outputSource: execute/data_dictionary
  execute_consolidated_data:
    type: File[]
    outputSource: execute/consolidated_data
  execute_shapes:
    type: {'type': 'array', 'items': {'type': 'array', 'items': ['File']}}
    outputSource: execute/shapes
  execute_aggregate_log:
    type: {'type': 'array', 'items': 'Any'}
    outputSource: execute/aggregate_log
  execute_aggregate_err:
    type: File[]
    outputSource: execute/aggregate_err
  execute_ingest_log:
    type: File
    outputSource: execute/ingest_log
  execute_index_log:
    type: File
    outputSource: execute/index_log
  execute_vacuum_log:
    type: File
    outputSource: execute/vacuum_log
  execute_ingest_err:
    type: File
    outputSource: execute/ingest_err
  execute_index_err:
    type: File
    outputSource: execute/index_err
  execute_vacuum_err:
    type: File
    outputSource: execute/vacuum_err
## Generated by nsaph/util/cwl_collect_outputs.py from run_test.cwl:
  verify_log:
    type: File
    outputSource: verify/log
  verify_errors:
    type: File
    outputSource: verify/errors
